export enum SocketRoomType {
    CHAT = 'CHAT',
    LIST = 'LIST'
}

export enum SocketEventType {
    CONNECT = 'CONNECT',
    CHAT_JOIN = 'CHAT_JOIN',
    MESSAGE = 'MESSAGE',
    DISCONNECT = 'DISCONNECT',
    DELIVERED_MESSAGE = 'DELIVERED_MESSAGE',
    READ_MESSAGE = 'READ_MESSAGE',
    REACT_MESSAGE = 'REACT_MESSAGE',
    ONLINE_STATUS = 'ONLINE_STATUS',
    SOCKET_ERROR = 'SOCKET_ERROR',
    SUBSCRIPTION_STATUS = 'SUBSCRIPTION_STATUS',
    LEAVE_ROOM = 'LEAVE_ROOM',
    CHAT_LIST = 'CHAT_LIST'
}
